apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-vault-token
  namespace: default
data:
  token: "aHZzLkNBRVNJTnpQMzNEYlh6VFNKYlljUWFaT0JfMkc5QWlNRGpuN1BCTE5rYmRnZlE1d0doNEtIR2gyY3k1eFVEWnNUa3hDV1RWRldXNHpURlV3VDBKcGVXd3dNamM="
